1 S2 -> Markov

# Add to the disjunction below any new POS tag that you might introduce in Vocab.gr. 
#This ensures that your grammar retains the ability to parse any given sequence of POS tags
1 Markov -> { Det | Misc | Noun | Prep | Proper | VerbT | EOS | Pause | Conj | NUM | Misc | VerbM | Adj | AdjC | AdjS | NounPl | NounProp | NounPropPl | Pronoun | PronounPs | Adv | Do | Does | TO | NOT | Verb | VerbP | VerbPrP | VerbPP | Verb3S | VerbPP3 | WhDet | WhPron | WhPoss | WhAdv | Poss} (Markov) 
